# nixpacks.toml (repo root)

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install -r backend/requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
# Try to align Alembic with existing tables (no script needed), then start
cmd = "cd backend && /app/.venv/bin/python -m flask --app app:app db stamp head || true; /app/.venv/bin/python -m gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT app:app"
