# nixpacks.toml
providers = ["python", "node"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION   = "20"

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
# Try migrations; if DB is already populated, stamp and continue.
cmd = "cd backend && (flask --app app:app db upgrade || flask --app app:app db stamp head || true) ; gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT app:app"
