cat > nixpacks.toml <<'TOML'
[setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && npm ci"
]

[build]
cmds = [
  "cd frontend && VITE_API_BASE=/ npm run build"
]

[start]
cmd = "gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT backend.wsgi:app"
TOML
