# Use only the python provider; we bring Node via nixPkgs to avoid npm conflicts.
providers = ["python"]

[phases.setup]
# Add Python + Node + curl so we can bootstrap pip if needed
nixPkgs = ["python311", "nodejs_20", "curl"]

[phases.install]
cmds = [
  # 1) Try ensurepip (may be disabled in Nix)
  "python -m ensurepip --upgrade || true",

  # 2) If pip still missing, bootstrap with get-pip.py (works reliably)
  "if ! command -v pip >/dev/null 2>&1; then curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && python /tmp/get-pip.py; fi",

  # 3) Upgrade toolchain & install backend deps
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install --no-cache-dir -r backend/requirements.txt",

  # 4) Frontend deps
  "c
