providers = ["python"]  # we’ll still add Node via nixPkgs

[phases.setup]
# Install Python 3.11, pip, and Node 20
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "nodejs_20"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip",
  "/app/.venv/bin/pip install -r backend/requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "./run_migration.sh && cd backend && /app/.venv/bin/python -m gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT app:app"
