providers = ["python"]  # Node comes via nixPkgs to avoid npm collisions

[phases.setup]
# Python 3.11 + virtualenv + Node 20 for the Vite build
nixPkgs = ["python311", "python311Packages.virtualenv", "nodejs_20"]

[phases.install]
cmds = [
  # Create project-local virtualenv at repo root
  "python -m venv .venv",
  # Install backend deps into the venv
  ".venv/bin/pip install -r backend/requirements.txt",
  # Install frontend deps
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  # Build the Vite frontend (outputs to frontend/dist)
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && ../.venv/bin/flask db upgrade || (../.venv/bin/flask db stamp head && echo 'Alembic stamped existing schema') ; ../.venv/bin/gunicorn -w 3 -k gthread -b 0.0.0.0:$PORT app:app"
