"""init schema

Revision ID: 9f1babc2b0db
Revises: 79992be89d2c
Create Date: 2025-08-09 17:25:34.094961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1babc2b0db'
down_revision = '79992be89d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casenote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casenote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casenote_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('case_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_note_participant_id'))

    op.drop_table('case_note')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('taken_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('checked_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_participant_last_first', ['last_name', 'first_name'], unique=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('provided_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('provided_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_last_first')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('milestone', schema=None) as batch_op:
        batch_op.alter_column('checked_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('employment', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('taken_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('case_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('participant_id', sa.INTEGER(), nullable=True),
    sa.Column('staff_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_note_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('casenote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casenote_participant_id'))

    op.drop_table('casenote')
    op.drop_table('provider')
    op.drop_table('employer')
    # ### end Alembic commands ###
